import html from "../assets/images/html-5.png";
import css from "../assets/images/css-3.png";
import javascript from "../assets/images/js.png";
import typescript from "../assets/images/typescript.png";
import Github from "../assets/images/github-sign.png";
import Linkedin from "../assets/images/linkedin.png";
import TR from "../assets/images/turkey.png";
import USA from "../assets/images/united-states-of-america.png";
import nextjs from "../assets/images/b.png";
import react from "../assets/images/a.png";
import nodejs from "../assets/images/c.png";
import mongodb from "../assets/images/a.png";
import firebase from "../assets/images/d.png";
import mysql from "../assets/images/mysql.png";
import postgresql from "../assets/images/postgresql.png";
import redis from "../assets/images/redis.png";
import cloudinary from "../assets/images/cloudinary.png";
import docker from "../assets/images/docker.png";
import kubernetes from "../assets/images/kubernetes.png";

export const WebTecnologies = [html, css, javascript, typescript];
export const FrontEndTecnologies = [react, nextjs];
export const backendTechnologiesImage = [nodejs];
export const nosqlImage = [mongodb, firebase];
export const sqlImages = [postgresql, mysql];
export const linkedin = Linkedin;
export const github = Github;
export const usa = USA;
export const tr = TR;
export { redis, cloudinary, docker, kubernetes };
